name: Deploy Quarto site
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Generate README pages
        run: |
          bash scripts/generate-readmes.sh
      - name: Render site
        run: |
          quarto render
      - uses: actions/upload-pages-artifact@v1
        with:
          path: _site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
